// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPWjKyyQ6r2mjVcPnFaW4f4U6kcEYfFNU',
    appId: '1:559677892507:web:850052c5636eddbf47e33e',
    messagingSenderId: '559677892507',
    projectId: 'flutterfirestore-1849e',
    authDomain: 'flutterfirestore-1849e.firebaseapp.com',
    storageBucket: 'flutterfirestore-1849e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHkR2-RyGg0hGs7u-a14Oq3otMaKREiU',
    appId: '1:559677892507:android:4052349a5924d44547e33e',
    messagingSenderId: '559677892507',
    projectId: 'flutterfirestore-1849e',
    storageBucket: 'flutterfirestore-1849e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAza3YMWHTC2oDFEJ-CI8_ThVyspZn3xC0',
    appId: '1:559677892507:ios:2c4baf73df9c04d747e33e',
    messagingSenderId: '559677892507',
    projectId: 'flutterfirestore-1849e',
    storageBucket: 'flutterfirestore-1849e.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAza3YMWHTC2oDFEJ-CI8_ThVyspZn3xC0',
    appId: '1:559677892507:ios:63d7576544da546247e33e',
    messagingSenderId: '559677892507',
    projectId: 'flutterfirestore-1849e',
    storageBucket: 'flutterfirestore-1849e.appspot.com',
    iosBundleId: 'com.example.flutterlist.RunnerTests',
  );
}
