// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFT7ato4E-GiLxnESa0LZUvIociRDIhFs',
    appId: '1:287529297350:web:ddf7957c939e8ac6e3bec7',
    messagingSenderId: '287529297350',
    projectId: 'notes-e6ed6',
    authDomain: 'notes-e6ed6.firebaseapp.com',
    databaseURL: 'https://notes-e6ed6-default-rtdb.firebaseio.com',
    storageBucket: 'notes-e6ed6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBky_1tZpYSfKPLaMxaKqbzNc4Ien3MUAY',
    appId: '1:287529297350:android:236b3a8ae516bee6e3bec7',
    messagingSenderId: '287529297350',
    projectId: 'notes-e6ed6',
    databaseURL: 'https://notes-e6ed6-default-rtdb.firebaseio.com',
    storageBucket: 'notes-e6ed6.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxW2C54hPKjn8N7bgB67yd8mlx6SRK4Fk',
    appId: '1:287529297350:ios:bf9f88b06c34e737e3bec7',
    messagingSenderId: '287529297350',
    projectId: 'notes-e6ed6',
    databaseURL: 'https://notes-e6ed6-default-rtdb.firebaseio.com',
    storageBucket: 'notes-e6ed6.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxW2C54hPKjn8N7bgB67yd8mlx6SRK4Fk',
    appId: '1:287529297350:ios:bf9f88b06c34e737e3bec7',
    messagingSenderId: '287529297350',
    projectId: 'notes-e6ed6',
    databaseURL: 'https://notes-e6ed6-default-rtdb.firebaseio.com',
    storageBucket: 'notes-e6ed6.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFT7ato4E-GiLxnESa0LZUvIociRDIhFs',
    appId: '1:287529297350:web:957e8fcd6b56bbebe3bec7',
    messagingSenderId: '287529297350',
    projectId: 'notes-e6ed6',
    authDomain: 'notes-e6ed6.firebaseapp.com',
    databaseURL: 'https://notes-e6ed6-default-rtdb.firebaseio.com',
    storageBucket: 'notes-e6ed6.appspot.com',
  );

}